### ISSUE TITLE
up主，这个没有生效，请问是什么原因呀

### ISSUE THREAD

**Issue by EangGeen** [mohenghui/detectAuto_v7#1]
C:\Users\Acer\.conda\envs\yolov7Demo1\python.exe D:/PyProj/yolo7/two/yolov7-main/detectAuto_v7-main/detect_auto.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Acer\.conda\envs\yolov7Demo1\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "D:\PyProj\yolo7\two\yolov7-main\detectAuto_v7-main\detect_auto.py", line 293, in tes06
    self.init_model()
  File "D:\PyProj\yolo7\two\yolov7-main\detectAuto_v7-main\detect_auto.py", line 47, in init_model
    self.model=attempt_load(self.weights, map_location=self.device)
  File "D:\PyProj\yolo7\two\yolov7-main\models\experimental.py", line 252, in attempt_load
    ckpt = torch.load(w, map_location=map_location)  # load
  File "C:\Users\Acer\AppData\Roaming\Python\Python39\site-packages\torch\serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\Acer\AppData\Roaming\Python\Python39\site-packages\torch\serialization.py", line 1046, in _load
    result = unpickler.load()
  File "C:\Users\Acer\AppData\Roaming\Python\Python39\site-packages\torch\serialization.py", line 1039, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'C3' on <module 'models.common' from 'D:\\PyProj\\yolo7\\two\\yolov7-main\\models\\common.py'>
Fusing layers... 
C:\Users\Acer\AppData\Roaming\Python\Python39\site-packages\torch\_tensor.py:1104: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\build\aten\src\ATen/core/TensorBody.h:475.)
  return self._grad
 Convert model to Traced-model... 
 traced_script_module saved! 
 model is traced! 

C:\Users\Acer\AppData\Roaming\Python\Python39\site-packages\torch\functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
frame_00001.jpg已标注完成
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Acer\.conda\envs\yolov7Demo1\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "D:\PyProj\yolo7\two\yolov7-main\detectAuto_v7-main\detect_auto.py", line 294, in tes06
    self.work()
  File "D:\PyProj\yolo7\two\yolov7-main\detectAuto_v7-main\detect_auto.py", line 239, in work
    if (self.predefined_classes.count(self.predefined_classes[label_id]) > 0):
IndexError: list index out of range

**Comment by mohenghui** [comment]
类别改了吗

**Comment by EangGeen** [comment]
刚刚试了一下，classes.txt里面只有person也会报错

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年12月11日 0:58
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [mohenghui/detectAuto_v7] up主，这个没有生效，请问是什么原因呀 (Issue #1)


类别改了吗

―

**Comment by mohenghui** [comment]
明天我看看。973733507



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月11日(周日) 凌晨1:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mohenghui/detectAuto_v7] up主，这个没有生效，请问是什么原因呀 (Issue #1)




 刚刚试了一下，classes.txt里面只有person也会报错 
 
 从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986&gt;发送 
 
 发件人: ***@***.***&gt; 
 发送时间: 2022年12月11日 0:58 
 收件人: ***@***.***&gt; 
 抄送: ***@***.***&gt;; ***@***.***&gt; 
 主题: Re: [mohenghui/detectAuto_v7] up主，这个没有生效，请问是什么原因呀 (Issue #1) 
 
 
 类别改了吗 
 
 ―

**Comment by IssacaLaw** [comment]
我也遇到同样的错误，请问一下大伙解决了吗？

**Comment by YuqiuDeng** [comment]
我也遇到同样的问题了，请问有人解决好了吗？

**Comment by mohenghui** [comment]
> 我也遇到同样的问题了，请问有人解决好了吗？

将脚本放到yolov7官方文件夹下

**Comment by YuqiuDeng** [comment]
> > 我也遇到同样的问题了，请问有人解决好了吗？
> 
> 将脚本放到yolov7官方文件夹下

还是报一样的错误大佬，你提供的v7克隆项目我也尝试过了😭。

**Comment by mohenghui** [comment]
> > > 我也遇到同样的问题了，请问有人解决好了吗？
> > 
> > 
> > 将脚本放到yolov7官方文件夹下
> 
> 还是报一样的错误大佬，你提供的v7克隆项目我也尝试过了😭。

vx 973733507 我看看
